version: '3.1'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: weRaceAsOneF12021
      MYSQL_USER: user
      MYSQL_PASSWORD: weRaceAsOneF12021
      MYSQL_DATABASE: F1DB
    ports:
      - 3306:3306

  adminer:
      depends_on:
         - db
  
      image: adminer
      restart: unless-stopped
      ports:
        - 8080:8080
  