version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: weRaceAsOneF12021
      MYSQL_USER: user
      MYSQL_PASSWORD: weRaceAsOneF12021
      MYSQL_DATABASE: F1DB
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
  
volumes:
  db_data: